spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fd_calculator
    username: root
    password: Abhi-iit10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect




pricing:
  api:
    url: http://localhost:8081
server:
  port: 8081


